[init_params]
input_size = 2
target_size = 1
num_hidden_layers = 2
num_neurons_per_hidden_layer = [3,2]
seed = 2137
activation_function = "relu"
epochs = 500

[train_params]


[data]
objective = "classification"
data_dir = "data"
data_size = 10000
data_name = "three_gauss"